name: Build React App and Deploy it to Container and Deploy the Container on Azure Web App

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  # Add more steps as needed for deploying or other actions.
  deploy-to-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t todolist-app:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag todolist-app:latest degr8sidcode/todolist-app:latest
          docker push degr8sidcode/todolist-app:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      ACR_REGISTRY: ${{ secrets.AZURE_REGISTRY_NAME }}
      ACR_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
      ACR_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        run: az acr login --name $ACR_REGISTRY

      - name: Build and push Docker image to ACR
        run: |
          docker build -t $ACR_REGISTRY.azurecr.io/your-app-name:latest .
          docker login $ACR_REGISTRY.azurecr.io -u $ACR_USERNAME -p $ACR_PASSWORD
          docker push $ACR_REGISTRY.azurecr.io/your-app-name:latest
        env:
          DOCKER_CLI_ACI_LOGIN: 1

      - name: Clean up
        run: docker logout $ACR_REGISTRY.azurecr.io
