name: Build React App and Deploy it to Container and Deploy the Container on Azure Web App


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: |
          docker build -t todolist-app:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag todolist-app:latest degr8sidcode/todolist-app:latest
          docker push degr8sidcode/todolist-app:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy on Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'todolistappdevops'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: './publish'
          
